name: nastachku_parser
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/guid-empty/nastachku-parser
author: andrey.smirnov <andrey.smirnov@team.wrike.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  html: ^0.13.4+1
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
